<?php $this->headTitle($this->title); // Titre de la page ?>

<?php 
// Header ADMIN
echo $this->partial('common/headerResponsable.phtml'); 
?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
	              <h2 class="panel-title"><?php echo $this->titreForm; ?>
	              	<a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'index', 'type'=>null, 'code'=>null)); ?>" class="navbar-right cursorHand"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour"/></a>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
					<?php // Affiche le formulaire d'etudiant ?>
					<?php echo $this->formEtudiant; ?>
				</div>
			</div>
		</div>
	</div>
</div>