<?php $this->headTitle($this->title); // Titre de la page
$unUtilisateur = $this->unUtilisateur;
$typeUtilisateur = $this->typeUtilisateur; 
$lesStages = $this->lesStages; 
?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
			
				<?php 
				// ENSEIGNANT
				if($typeUtilisateur == "Enseignant") { 
				?>
					<div class="panel-heading">
						<h2 class="panel-title"><?php echo $unUtilisateur->nomEnseignant.' '.$unUtilisateur->prenomEnseignant.' | '.$unUtilisateur->fonctionEnseignant.' | '.$unUtilisateur->specialiteEnseignant; 
													  if($unUtilisateur->isResponsableSiteEnseignant) echo ' | Responsable'; ?>
						 	<a class="navbar-right" href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'index', 'code'=>null, 'type'=>null)); ?>"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour" /></a>
						</h2>
		            </div>
		      	<?php } 
				// ETUDIANT
				else if($typeUtilisateur == "Etudiant") { 
				?>
					<div class="panel-heading">
						<h2 class="panel-title"><?php echo $unUtilisateur->nomEtudiant.' '.$unUtilisateur->prenomEtudiant.' | '.$unUtilisateur->libelleFormation.' '.$unUtilisateur->niveauFormation.' '.$unUtilisateur->specialiteFormation; ?>
						 	<a class="navbar-right" href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'index', 'code'=>null, 'type'=>null)); ?>"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour" /></a>
						</h2>
		            </div>
		        <?php }
				// ENTREPRISE
		        else if($typeUtilisateur == "Entreprise") {
		        	?>
        			<div class="panel-heading">
        				<h2 class="panel-title"><?php echo $unUtilisateur->rsEntreprise; ?>
        				 	<a class="navbar-right" href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'index', 'code'=>null, 'type'=>null)); ?>"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour" /></a>
        				</h2>
        				<?php echo "Dirigeant : <strong>$unUtilisateur->nomPersonne $unUtilisateur->prenomPersonne</strong><br />
									Adresse : <strong>$unUtilisateur->adrRueEntreprise - $unUtilisateur->adrVilleEntreprise - $unUtilisateur->adrCpEntreprise</strong> <br />
		        					Tél : <strong>$unUtilisateur->telEntreprise</strong> <br />
		        					Mél : <strong>$unUtilisateur->emailEntreprise</strong>"; 
		        		?>
        		    </div>
		        <?php } ?>  
		      	
	            <div class="panel-body">
				  	<?php if(count($lesStages) > 0) { ?>
					  	<!-- Table -->
						<table class="table text-center">
						<caption><h3><span class="label label-primary">&nbsp; Liste des stages &nbsp;</span></h3></caption>
							<thead>
								<tr>
									<?php if($typeUtilisateur != "Etudiant") { ?><th class="text-center">Étudiant</th><?php } ?>
									<th class="text-center">Stage</th>
									<th class="text-center">Date début stage</th>
									<th class="text-center">Date fin stage</th>
				          		</tr>
			        		</thead>
			        		<tbody>
			        		<?php foreach($lesStages as $unStage) { ?>
								<tr>
									<?php if($typeUtilisateur != "Etudiant") { echo "<td>"; echo $unStage->nomEtudiant.' '.$unStage->prenomEtudiant; echo "</td>"; } ?>
				            		<td><?php echo $unStage->libelleStage; ?></td>
						            <td><?php echo $unStage->dateDebutStage; ?></td>
						            <td><?php echo $unStage->dateFinStage; ?></td>
						            <td></td>
								</tr>
							<?php } ?>
			        		</tbody>
		      			</table>
		      		<?php } else if($typeUtilisateur == "Enseignant") { echo "Aucun stage tutoré."; } 
		        		else if($typeUtilisateur == "Etudiant") { echo "Aucun stage."; } 
		        		else if($typeUtilisateur == "Entreprise") { echo "Aucun stage déposé."; }
		        	?>
				</div>
			</div>
		</div>
	</div>
</div>