<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
		
			<?php // ENSEIGNANT ?>
			<div class="panel col-md-4">
				<div class="panel-heading">
	              <h2 class="panel-title">
	              		Enseignant 
  					  	<a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'depot', 'type'=>'Enseignant'),"default", true); ?>" class="btn btn-success pull-right stageEtudiantBtnLeft">Ajouter enseignant &raquo;</a>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
	            	<?php 
	            	if(count($this->lesEnseignants) > 0) {
	            		foreach($this->lesEnseignants as $unEnseignant) { ?>          
						<ul class="list-group">
						  <li class="list-group-item list-group-item-info">
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'delete', type=>'Enseignant', 'code'=>$unEnseignant->idEnseignant)); ?>" class="pull-right"><img src="<?php echo $this->baseUrl();?>/images/icone/delete.png" alt="Etudiant" class="btnCrudResponsable" alt="Supprimer" /></a>
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'fiche', type=>'Enseignant', 'code'=>$unEnseignant->idEnseignant)); ?>" class="pull-right"><img src="<?php echo $this->baseUrl();?>/images/icone/edit.png" alt="Etudiant" class="btnCrudResponsable" alt="Modifier" /></a>
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'fiche', 'code'=>$unEnseignant->idEnseignant, 'type'=>'Enseignant')); ?>">
								<?php echo $unEnseignant["nomEnseignant"].' '.$unEnseignant['prenomEnseignant']; ?>
						  	</a>
						  </li>
						</ul>
						<?php 
						}
						// Pagination
						echo $this->paginationControl($this->lesEnseignants,'Sliding','common/paginationEnseignant.phtml'); 
					}
					// Liste de stage vide 
					else echo "Aucun enseignant n'a été trouvé."; ?>
	            </div>
			</div>
			
			
			
			
			<?php // ETUDIANT ?>
			<div class="panel col-md-4">
				<div class="panel-heading">
	              <h2 class="panel-title">
	              		Étudiant 
	              		<a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'depot', 'type'=>'Etudiant'),"default", true); ?>" class="btn btn-success pull-right stageEtudiantBtnLeft">Ajouter étudiant &raquo;</a>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
	            	<?php 
	            	if(count($this->lesEtudiants) > 0) {
	            		foreach($this->lesEtudiants as $unEtudiant) { ?>          
						<ul class="list-group">
						  <li class="list-group-item list-group-item-info">
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'delete', type=>'Etudiant', 'code'=>$unEtudiant->ineEtudiant)); ?>" class="pull-right"><img src="<?php echo $this->baseUrl();?>/images/icone/delete.png" alt="Etudiant" class="btnCrudResponsable" alt="Supprimer" /></a>
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'fiche', type=>'Etudiant', 'code'=>$unEtudiant->ineEtudiant)); ?>" class="pull-right"><img src="<?php echo $this->baseUrl();?>/images/icone/edit.png" alt="Etudiant" class="btnCrudResponsable" alt="Modifier" /></a>
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'fiche', 'code'=>$unEtudiant->ineEtudiant, 'type'=>'Etudiant')); ?>">
								<?php echo $unEtudiant->nomEtudiant.' '.$unEtudiant->prenomEtudiant; ?>
						  	</a>
						  </li>
						</ul>
						<?php 
						}
						// Pagination
						echo $this->paginationControl($this->lesEtudiants,'Sliding','common/paginationEtudiant.phtml'); 
					}
					// Liste de stage vide 
					else echo "Aucun etudiant n'a été trouvé."; ?>
	            </div>
			</div>
			
			
			
			
			<?php // ENTREPRISE ?>
			<div class="panel col-md-4">
				<div class="panel-heading">
	              <h2 class="panel-title">
	              		Entreprise <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'depot', 'type'=>'Entreprise'),"default", true); ?>" class="btn btn-success pull-right stageEtudiantBtnLeft">Ajouter entreprise &raquo;</a>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
	            	<?php 
	            	if(count($this->lesEntreprises) > 0) {
	            		foreach($this->lesEntreprises as $uneEntreprise) { ?>          
						<ul class="list-group">
						  <li class="list-group-item list-group-item-info">
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'delete', type=>'Entreprise', 'code'=>$uneEntreprise->idEntreprise)); ?>" class="pull-right"><img src="<?php echo $this->baseUrl();?>/images/icone/delete.png" class="btnCrudResponsable" alt="Supprimer" /></a>
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'fiche', type=>'Entreprise', 'code'=>$uneEntreprise->idEntreprise)); ?>" class="pull-right"><img src="<?php echo $this->baseUrl();?>/images/icone/edit.png" class="btnCrudResponsable" alt="Modifier" /></a>
						   <a href="<?php echo $this->url(array('controller'=>'responsable', 'action'=>'fiche', 'code'=>$uneEntreprise->idEntreprise, 'type'=>'Entreprise')); ?>">
								<?php echo $uneEntreprise->rsEntreprise; ?>
						  	</a>
						  </li>
						</ul>
						<?php 
						}
						// Pagination
						echo $this->paginationControl($this->lesEntreprises,'Sliding','common/paginationEntreprise.phtml'); 
					}
					// Liste de stage vide 
					else echo "Aucune entreprise n'a été trouvé."; ?>
	            </div>
			</div>
			
		</div>
	</div>
</div>
