<?php
// Titre de la page
$this->title = "Mot de passe oublié";
// Titre de la section
$this->headTitle($this->title);
?>	

<div id="blockMdpForget">	
	<h3>Récupération du mot de passe</h3>
		<h5 id="messageMdpForget"><?php echo $this->message; ?></h5>
	<p id="info">
		Pour recevoir le mot de passe de votre compte par e-mail, 
		il suffit d'indiquer votre adresse e-mail utilisée lors de la création de votre compte. 
		<br />
		Vous recevrez dans les minutes suivantes un e-mail avec votre nouveau mot de passe, 
		toutefois il vous est conseillé de le modifier par la suite.
	</p>
	
	<p>
		<?php // Formulaire d'envoie ?>
		<?php echo $this->formMdpForget; ?>
	</p>

	<br />
	
	<h4>Informations</h4>
	<p id="infoSup"> Votre compte vous permet de bénéficier des services du site tels que : </p>
	<ul>
        <li>Commander vos articles </li>         
        <li>Bénéficier de promotion</li>
        <li>Suivre le traitement de vos commandes </li>
        <li>Donner votre avis sur les livres </li>
	</ul>
</div>

	