<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<h1>
			Université de Perpignan Via Domitia <br /> Licence 3 Informatique
		</h1>
		<p>Ce site web permet de gérer les stages des étudiants de l’UPVD.</p>
		<p>
			<a class="btn btn-primary btn-lg" href="http://offre-formation.univ-perp.fr/fr/_modules/education/education.html?educationid=FR_RNE_0660437S_PR_1389693686201&searchWord=informatique" role="button" target="_blank">En savoir plus sur la formation &raquo;</a>
		</p>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-heading">
              <h2 class="panel-title">Intervenant</h2>
            </div>
            
            <div class="panel-body">
				<div class="col-md-4">
					<h3>Entreprise</h3>
					<p>Les entreprises, qui proposent un stage, lui affectent un tuteur (salarié) de l’entreprise, ce dernier pouvant assister à la soutenance du ou des stages dont il est le tuteur.</p>
					<?php // <p><a class="btn btn-primary" href="#" role="button">Plus d'infos &raquo;</a></p> ?>
				</div>
				
				<div class="col-md-4">
					<h3>Enseignant</h3>
					<p>Les enseignants responsables du site ainsi que les tuteurs peuvent consulter la liste des stages (ainsi que des entreprises,...) effectués par les étudiants dont ils sont tuteur.</p>
					<?php // <p><a class="btn btn-primary" href="#" role="button">Plus d'infos &raquo;</a></p> ?>
				</div>
				
				<div class="col-md-4">
					<h3>Etudiant</h3>
					<p>Les étudiant qui recherchent un stage parmi les offres validées.</p>
					<?php // <br/><br/><p><a class="btn btn-primary" href="#" role="button">Plus d'infos &raquo;</a></p> ?>
				</div>
          	</div>
		</div>
	</div>
</div>