<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
	              <h2 class="panel-title">Modèle logique des données [MLD]</h2>
	            </div>
	            
	            <div class="panel-body">
					<div class="col-md-12">
						<p id="mldText">
							<strong>Enseignant</strong>(<u>idEnseignant</u>, nomEnseignant, prenomEnseignant, fonctionEnseignant, specialiteEnseignant, loginEnseignant, mdpEnseignant, isResponsableSiteEnseignant) <br /><br />
							<strong>Entreprise</strong>(<u>siretEntreprise</u>, #idPersonneDirigeant, rsEntreprise, adrRueEntreprise, adrCpEntreprise, adrVilleEntreprise, telEntreprise, emailEntreprise, loginEntreprise, mdpEntreprise) <br /><br />
							<strong>Etudiant</strong>(<u>ineEtudiant</u>, #idFormation, nomEtudiant, prenomEtudiant, loginEtudiant, mdpEtudiant, emailEtudiant) <br /><br />
							<strong>Formation</strong>(<u>codeFormation</u>, #idEnseignantResponsable, libelleFormation, niveauFormation, specialiteFormation) <br /><br />
							<strong>Personne</strong>(<u>idPersonne</u>, #idEntrepriseTravail, nomPersonne, prenomPersonne, fonctionPersonne, telPortPersonne, telPostePersonne, emailPersonne) <br /><br />
							<strong>Soutenance</strong>(<u>idSoutenance</u>, dateSoutenance, salleSoutenance) <br /><br />
							<strong>Stage</strong>(<u>codeStage</u>, #idEntreprise, #idTuteur, libelleStage, descriptionStage, dateDebutStage, dateFinStage, etatStage) <br /><br />
							<strong>EnseignerFormationEnseignant</strong>(<u>#idFormation, #idEnseignant</u>) <br /><br />
							<strong>ConcernerFormationStage</strong>(<u>#idFormation, #idStage</u>) <br /><br />
							<strong>RealiserEtudiantStage</strong>(<u>#idEtudiant, #idStage</u>, #idEnseignantTuteur, #idSoutenance) <br /><br />
							<strong>DemandeEtudiantStage</strong>(<u>#idEtudiant, #idStage</u>) <br /><br />
						</p>
					</div>
	          	</div>
			</div>
		</div>
	</div>
</div>