<?php $this->headTitle($this->title); // Titre de la page ?>
<?php $unStage = $this->stage; ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
			
				<div class="panel-heading">
					<h2 class="panel-title"><?php echo $unStage->libelleStage; ?>
					 	<a class="navbar-right" href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index'),"default", true); ?>"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour" /></a>
					</h2>
	            </div>
	            
	            <div class="panel-body">
					<?php echo $unStage->descriptionStage; ?>
					
					<br /><br />
					
				  	<!-- Table -->
					<table class="table">
						<thead>
							<tr>
								<?php if($unStage->idEtudiant != null) { ?><th>Étudiant</th><?php } ?>
								<?php if($unStage->idEnseignantTuteur != null) { ?><th>Tuteur enseignant</th><?php } ?>
								<th>Tuteur entreprise</th>
								<th>Date début</th>
								<th>Date fin</th>
								<th>État</th>
			          		</tr>
		        		</thead>
		        		
		        		<tbody>
							<tr>
								<?php if($unStage->idEtudiant != null) { ?><td><?php echo $unStage->nomEtudiant.' '.$unStage->prenomEtudiant; ?></td><?php } ?>
								<?php if($unStage->idEnseignantTuteur != null) { ?><td><?php echo $unStage->nomEnseignant.' '.$unStage->prenomEnseignant; ?></td><?php } ?>
			            		<td><?php echo $unStage->nomPersonne.' '.$unStage->prenomPersonne; ?></td>
					            <td><?php echo $unStage->dateDebutStage; ?></td>
					            <td><?php echo $unStage->dateFinStage; ?></td>
					            <td><?php 
					            	if($unStage->etatStage == 1) echo "Validé"; 
					            	if($unStage->etatStage == 0) echo "En attente de validation";
					            	else if($unStage->etatStage == -1) echo "Refusé";
					            ?></td>
							</tr>
		        		</tbody>
	      			</table>
	      		</div>
	      		
			</div>
		</div>
	</div>
</div>
