<?php 
$this->headTitle($this->title); // Titre de la page 
$unStage = $this->stage; // Information du stage
$lesDemandes = $this->lesDemandes; // Les demandes de stages des etudiants
?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
			
				<div class="panel-heading">
					<h2 class="panel-title"><?php echo $unStage->libelleStage; ?>
					 	<span onclick="history.back()" class="navbar-right cursorHand"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour" /></span>
					</h2>
	            </div>
	            
	            <div class="panel-body">
					<?php echo $unStage->descriptionStage; ?>
					
					<br /><br />
					
				  	<!-- Table -->
					<table class="table text-center">
						<thead>
							<tr>
								<?php if($unStage->idEtudiant != null) { ?><th class="text-center">Étudiant</th><?php } ?>
								<?php if($unStage->idEnseignantTuteur != null) { ?><th class="text-center">Tuteur enseignant</th><?php } ?>
								<th class="text-center">Tuteur entreprise</th>
								<th class="text-center">Date début</th>
								<th class="text-center">Date fin</th>
								<th class="text-center">État</th>
			          		</tr>
		        		</thead>
		        		
		        		<tbody>
							<tr>
								<?php if($unStage->idEtudiant != null) { ?><td><?php echo $unStage->nomEtudiant.' '.$unStage->prenomEtudiant; ?></td><?php } ?>
								<?php if($unStage->idEnseignantTuteur != null) { ?><td><?php echo $unStage->nomEnseignant.' '.$unStage->prenomEnseignant; ?></td><?php } ?>
			            		<td><?php echo $unStage->nomPersonne.' '.$unStage->prenomPersonne; ?></td>
					            <td><?php echo $this->toDmy($unStage->dateDebutStage); ?></td>
					            <td><?php echo $this->toDmy($unStage->dateFinStage); ?></td>
					            <td><?php 
					            	if($unStage->etatStage == 0) echo "En attente d'activation par l'administration";
					            	else if($unStage->etatStage == -1) echo "Refusé";
					            	else if($unStage->idEtudiant != null && $unStage->idEnseignantTuteur != null) echo "Validé";
					            	else if($unStage->idEtudiant != null && $unStage->idEnseignantTuteur == null) echo "En attente de validation";
					            	else if($unStage->idEtudiant == null && $unStage->idEnseignantTuteur == null && $unStage->etatStage == 1) echo "Disponible";
					            ?></td>
							</tr>
		        		</tbody>
	      			</table>
	      			
	      			<?php 
	      			// ETUDIANT 
	      			if($this->typeSession == "Etudiant" && $unStage->idEtudiant == null && $unStage->idEnseignantTuteur == null) { ?><a id="confirmDemande" href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'demande', 'code'=>$unStage->codeStage),"default", true); ?>" class="btn btn-primary navbar-right stageEtudiantBtnLeft">Faire la demande de stage &raquo;</a><?php }
	      			else if($this->typeSession == "Etudiant" && $unStage->idEtudiant != null && $unStage->idEnseignantTuteur == null) { ?><a id="cancelDemande" href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'canceldemande', 'code'=>$unStage->codeStage),"default", true); ?>" class="btn btn-primary navbar-right stageEtudiantBtnLeft">&laquo; Annuler la demande de stage</a><?php }
	      			
	      			// ENTREPRISE
	      			if($this->typeSession == "Entreprise" && $unStage->etatStage != 1) { ?>
		      			<?php // Modifier Stage ?>
	      				<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'depot', 'code'=>$unStage->codeStage),"default", true); ?>" class="btn btn-primary navbar-right stageEtudiantBtnLeft">Modifier le stage &raquo;</a>
		      			<?php // Supprimer Stage ?>
		      			<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'delete', 'code'=>$unStage->codeStage),"default", true); ?>" class="btn btn-danger navbar-right stageEtudiantBtnLeft" id="confirmerDeleteStage">Supprimer le stage &raquo;</a>
		      		<?php }
	      			
	      			// ENSEIGNANT RESPONSABLE
	      			if($this->typeSession == "Enseignant" && $this->isResponsable == true) { ?>
	      				<?php // MODIFIER LE STAGE ?>
	      				<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'stageresponsable', 'code'=>$unStage->codeStage),"default", true); ?>" class="btn btn-primary navbar-right stageEtudiantBtnLeft">Modfier le stage &raquo;</a>
	      				
	      				<?php // LISTE DES DEMANDES DE STAGES ?>
	      				<?php if(count($lesDemandes) > 0) { ?>
					  	<!-- Table -->
						<table class="table text-center">
						<caption><h3><span class="label label-primary">&nbsp; Liste des demandes d'étudiants &nbsp;</span></h3></caption>
							<thead>
								<tr>
									<th class="text-center">Étudiant</th>
									<th class="text-center">Action</th>
				          		</tr>
			        		</thead>
			        		<tbody>
			        		<?php foreach($lesDemandes as $uneDemande) { ?>
								<tr>
									<td><?php echo $uneDemande->nomEtudiant. ' '.$uneDemande->prenomEtudiant; ?></td>
				            		<td><a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'demande', 'code'=>$unStage->codeStage, 'etudiant'=>$uneDemande->idEtudiant)); ?>" class="btn btn-success stageEtudiantBtnLeft">&nbsp;&nbsp; Valider la demande &raquo; &nbsp;&nbsp;</a></td>
								</tr>
							<?php } ?>
								<tr><td></td><td></td></tr>
								<tr><td colspan="2"><a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'demande', 'code'=>$unStage->codeStage, 'etudiant'=>"delete")); ?>" class="btn btn-danger stageEtudiantBtnLeft" id="confirmerDeleteDemandes">&nbsp;&nbsp; Supprimer les demandes &raquo; &nbsp;&nbsp;</a></td></tr>
			        		</tbody>
		      			</table>
		      			<?php } ?>
	      				
	      				<?php /*
						// Desactiver le stage	
	      				if($unStage->etatStage == 1) { ?>
	      					<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'updateetat', 'code'=>$unStage->codeStage, 'etat'=>-1),"default", true); ?>" class="btn btn-danger navbar-right stageEtudiantBtnLeft" id="confirmDesactiveStage">Désactiver le stage &raquo;</a>
	      				<?php 
						// Activer le stage					
						} else if($unStage->etatStage == -1) { ?>
		      				<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'updateetat', 'code'=>$unStage->codeStage, 'etat'=>1),"default", true); ?>" class="btn btn-success navbar-right stageEtudiantBtnLeft">&nbsp;&nbsp; Activer le stage &raquo; &nbsp;&nbsp;</a>
      					<?php  				
      					// Attente de validation du stage
      					} else { ?>
      						<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'updateetat', 'code'=>$unStage->codeStage, 'etat'=>-1),"default", true); ?>" class="btn btn-danger navbar-right stageEtudiantBtnLeft" id="confirmDesactiveStage">Désactiver le stage &raquo;</a>
      						<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'updateetat', 'code'=>$unStage->codeStage, 'etat'=>1),"default", true); ?>" class="btn btn-success navbar-right stageEtudiantBtnLeft">&nbsp;&nbsp; Activer le stage &raquo; &nbsp;&nbsp;</a>
      					<?php 
						// Retirer enseignant tuteur
						} if($unStage->idEnseignantTuteur != null) { ?>
	      					<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'retirerenseignant', 'code'=>$unStage->codeStage),"default", true); ?>" class="btn btn-primary navbar-right stageEtudiantBtnLeft" id="confirmRetirerEnseignant">Retirer enseignant tuteur &raquo;</a>
	      				<?php 
						// Retirer etudiant
						} if($unStage->idEtudiant != null) { ?>
	      					<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'retireretudiant', 'code'=>$unStage->codeStage, 'etudiant'=>$unStage->idEtudiant),"default", true); ?>" class="btn btn-info navbar-right stageEtudiantBtnLeft" id="confirmRetirerEtudiant">Retirer étudiant &raquo;</a>
	      				<?php } ?>
	      			<?php */
					} 
					?>
	      		</div>
	      		
			</div>
		</div>
	</div>
</div>

<?php // DIALOG DE CONFIRMATION ?>
<p id="dialog-confirm-delete-stage" title="Supprimer stage"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment supprimer ce stage ?</p>
<p id="dialog-confirm-delete-demandes" title="Supprimer demandes de stage"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment supprimer les demandes pour ce stage ?</p>
<p id="dialog-confirm-accept" title="Demande de stage"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment faire cette demande de stage ?</p>
<p id="dialog-confirm-cancel" title="Demande de stage"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment annuler cette demande de stage ?</p>

<p id="dialog-confirm-desactive-stage" title="Etat du stage"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment désactiver le stage ?</p>
<p id="dialog-confirm-retirer-enseignant" title="Retirer enseignant tuteur"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment retirer l'enseignant tuteur ?</p>
<p id="dialog-confirm-retirer-etudiant" title="Retirer étudiant"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment retirer l'étudiant ?</p>


<?php // SCRIPT JS UI POUR LE DIALOG ?>
<script>
$(function() {
	var hrefDemande = ''; // Variable qui recupere le chemin url en cas de redirection

	$("#dialog-confirm-accept").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 475,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#dialog-confirm-cancel").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 485,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#dialog-confirm-desactive-stage").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 395,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#dialog-confirm-retirer-enseignant").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 445,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#dialog-confirm-retirer-etudiant").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 365,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#dialog-confirm-delete-stage").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 400,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#dialog-confirm-delete-demandes").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 545,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#confirmDemande").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-accept").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});

	$("#cancelDemande").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-cancel").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});

	$("#confirmDesactiveStage").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-desactive-stage").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});

	$("#confirmRetirerEnseignant").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-retirer-enseignant").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});

	$("#confirmRetirerEtudiant").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-retirer-etudiant").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});

	$("#confirmerDeleteStage").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-delete-stage").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});

	$("#confirmerDeleteDemandes").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-delete-demandes").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});
});
</script>
 
