<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
		
			<div class="panel panel-default">
				<div class="panel-heading">
	              <h2 class="panel-title">
	              	  <?php if($this->typeSession == "Etudiant" && $this->param == null) { echo "Liste des stages disponible"; }
	              	  		else if($this->typeSession == "Etudiant" && $this->param == "stage") { echo "Liste de mes stages"; }
	              	  		else if($this->typeSession == "Etudiant" && $this->param == "demande") { echo "Liste de mes demandes de stage"; }
							
							else if($this->typeSession == "Enseignant" && $this->param == "tuteur" && $this->isResponsable == 1) { echo "Liste de mes stages"; }
							
							else { echo "Liste des stages"; } 
					  ?>
		              
		              <?php // FILTRE ETUDIANT RIGHT ?>
		              <?php if($this->typeSession == "Etudiant" && $this->param == "stage") { ?> 
		              			<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index', 'my'=>'demande'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Mes demandes &raquo;</a> 
		              			<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index'),"default", true); ?>" class="btn btn-default navbar-right">Tous les stages &raquo;</a>
		              <?php }
		              		else if($this->typeSession == "Etudiant" && $this->param == "demande") { ?>
		              		<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index', 'my'=>'stage'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Mes stages &raquo;</a>
		              		<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index'),"default", true); ?>" class="btn btn-default navbar-right">Tous les stages &raquo;</a> 
		              <?php } else if($this->typeSession == "Etudiant" && $this->param == null) { ?>
		              		<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index', 'my'=>'stage'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Mes stages &raquo;</a>
		              		<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index', 'my'=>'demande'),"default", true); ?>" class="btn btn-default navbar-right">Mes demandes &raquo;</a> 
		              <?php } ?>
					  
					  <?php if($this->typeSession == "Enseignant" && $this->param == "tuteur" && $this->isResponsable == 1) { ?> 
								<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Tous les stages &raquo;</a> 
					  <?php } else if($this->typeSession == "Enseignant" && $this->param == null && $this->isResponsable == 1) { ?>
								<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'index', 'my'=>'tuteur'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Mes stages &raquo;</a> 
					  <?php } ?>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
	            	<?php if(count($this->lesStages) > 0) { ?>
		            	<div class="list-group">
		            		<span class="btn list-group-item-success" id="btnLegendStage">&nbsp;&nbsp; Validé &nbsp;&nbsp;</span>
		            		<span class="btn list-group-item-info" id="btnLegendStage">&nbsp;&nbsp; En attente &nbsp;&nbsp;</span>
		            		<span class="btn list-group-item-danger" id="btnLegendStage">&nbsp;&nbsp; Refusé &nbsp;&nbsp;</span>
		            		<?php if($this->typeSession == "Entreprise") { ?><span><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_003_user.png" alt="Etudiant" class="legendeEtudiantAffecteStage" /> Étudiant affecté</span><?php } ?>
		            	</div>
	            
		            	<?php foreach($this->lesStages as $unStage) { ?>          
							<div class="list-group">
								<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'fiche', 'code'=>$unStage["codeStage"]),"default", true); ?>" 
								   class="list-group-item <?php if($unStage["etatStage"] == 1) { ?>list-group-item-success<?php }
								   						  		else if($unStage["etatStage"] == 0) { ?>list-group-item-info<?php }
								   						  		else if($unStage["etatStage"] == -1) { ?>list-group-item-danger<?php } ?>">
									<h4 class="list-group-item-heading"><?php echo $unStage["libelleStage"]; ?>
										<?php if(isset($unStage["isFindEtudiant"]) && $unStage["isFindEtudiant"] == true) { ?><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_003_user.png" alt="Etudiant" class="iconEtudiantLibStage"/><?php } ?>
									</h4>
									<div class="list-group-item-text"><?php echo $unStage["descriptionStage"]; ?></div>
							  	</a>
							</div>
						<?php }
						}
						// Liste de stage vide 
						else { 
							echo "Aucun stage n'a été trouvé."; 
							if($this->typeSession == "Entreprise") { ?>
							<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'depot'),"default", true); ?>" class="btn btn-primary">Déposer un stage &raquo;</a>
						<?php 
							} 
						} ?>
	            </div>
			</div>
			
		</div>
	</div>
</div>
