<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
	              <h2 class="panel-title"><?php echo $this->titreStage ?>
	              	<span onclick="history.back()" class="navbar-right cursorHand"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour"/></span>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
					<?php // Affiche le formulaire de d'un stage ?>
					<?php echo $this->formStage; ?>
				</div>
			</div>
		</div>
	</div>
</div>