<?php if ($this->pageCount): ?>
	<ul class="pagination">
		<!-- Premiere page -->
		<?php if (isset($this->first) && $this->current != $this->first): ?>
			 <li><a href="<?php echo $this->url(array('pageEnseignant' => $this->first)); ?>">Début</a></li>
		<?php else: ?>
			  <li class="disabled"><span>Début</span></li>
		<?php endif; ?>
		
		<!-- Page précédente -->
		<?php if (isset($this->previous)): ?>
			 <li><a href="<?php echo $this->url(array('pageEnseignant' => $this->previous)); ?>">&laquo;</a></li>
		<?php else: ?>
			  <li class="disabled"><span>&laquo;</span></li>
		<?php endif; ?>
		
		<!-- Numéro des pages -->
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<li><a href="<?php echo $this->url(array('pageEnseignant' => $page)); ?>"><?php echo $page; ?></a></li>
			<?php else: ?>
				<li class="active"><span><?php echo $page; ?></span></li>
			<?php endif; ?>
		<?php endforeach; ?>
		
		<!-- Page suivante -->
		<?php if (isset($this->next)): ?>
			<li><a href="<?php echo $this->url(array('pageEnseignant' => $this->next)).""; ?>">&raquo;</a></li>
		<?php else: ?>
			<li class="disabled"><span>&raquo;</span></li>
		<?php endif; ?>
		
		<!-- Derniere page -->
		<?php if (isset($this->last) && $this->current != $this->last): ?>
			<li><a href="<?php echo $this->url(array('pageEnseignant' => $this->last)).""; ?>">Fin</a></li>
		<?php else: ?>
			<li class="disabled"><span>Fin</span></li>
		<?php endif; ?>
	</ul>
<?php endif; ?>