<?php if ($this->pageCount): ?>
	<div id="pagination">
		<!-- Page précédente -->
		<?php if (isset($this->previous)): ?>
			 <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" id="btnPage">Précédent</a>
		<?php else: ?>
			  <span class="disable">Précédent</span>
		<?php endif; ?>
		
		<!-- Numéro des pages -->
		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<a href="<?php echo $this->url(array('page' => $page)); ?>" id="numPage"><?php echo $page; ?></a>
			<?php else: ?>
				<span id="currentPage"><?php echo $page; ?></span>
			<?php endif; ?>
		<?php endforeach; ?>
		
		<!-- Page suivante -->
		<?php if (isset($this->next)): ?>
			<a href="<?php echo $this->url(array('page' => $this->next)).""; ?>" id="btnPage"> Suivant</a>
		<?php else: ?>
			<span class="disable">Suivant</span>
		<?php endif; ?>
	</div>
<?php endif; ?>