<?php
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" lang="fr">
<head>
<?php 
// TITRE
echo $this->headTitle()	->setSeparator(' - ')
						->headTitle('UPVD');
// META
echo $this->headMeta()	->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8')
						->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
						->appendHttpEquiv('Cache-Control', 'no-cache')
						->appendName('viewport', 'width=device-width, initial-scale=1')
						->appendName('description', 'Site web permettant la gestion des stages des étudiants de l’UPVD. Projet L3 Informatique.')
						->appendName('author', 'Frederic CANO, Mickael Campoy');
// CSS
echo $this->headLink()	->prependStylesheet($this->baseUrl().'/style/bootstrap/bootstrap.css')
						->prependStylesheet($this->baseUrl().'/style/ui/jquery-ui-1.10.4.custom.css')
						->prependStylesheet($this->baseUrl().'/style/style.css');
echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => 'images/icone/logo.ico'),'PREPEND');
// JS
echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery.js') 
						->appendFile($this->baseUrl().'/js/jquery.easing.js') 
						->appendFile($this->baseUrl().'/js/jquery-ui-1.10.4.custom.js') 
						->appendFile($this->baseUrl().'/js/bootstrap.min.js')
						->appendFile($this->baseUrl().'/js/script.js');

?>
</head>
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	<body class="ie">
<![endif]-->
<!--[if IE 9]><body class="ie ie9"><![endif]-->
<!--[if !IE]><!--><body><!--<![endif]-->
<?php 
	// Header
	echo $this->partial('common/header.phtml');
	
	// Contenu des pages
	echo $this->flashMessages(); // Flash Messager
	echo $this->layout()->content; // Contenu de la page (view)
	
	// Footer
	echo $this->partial('common/footer.phtml');	
?>
</body>
</html>