<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
	              <h2 class="panel-title">Dépot de stage
	              	<span onclick="history.back()" class="navbar-right cursorHand"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour"/></span>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
					<?php // Affiche le formulaire de depot de stage ?>
					<?php echo $this->formDepotSoutenance; ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$(function() {
		$("#dateHeure").datepicker({ minDate: 0, maxDate: "+1Y +1D", dateFormat: 'yy-mm-dd' });
  	});
</script>
