<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
	              <h2 class="panel-title"><?php echo $this->libelleTitre; ?> d'une soutenance
	              	<span onclick="history.back()" class="navbar-right cursorHand"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour"/></span>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
					<?php // Affiche le formulaire de depot de stage ?>
					<?php echo $this->formDepotSoutenance; ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	$(function() {
		$('#dateSoutenance').datetimepicker({
			lang:'fr',
			mask:true,
			minTime:'07:00',
			maxTime:'20:00',
			minDate:'-1970/01/01',
		 	onGenerate:function( ct ){
				jQuery(this).find('.xdsoft_date.xdsoft_weekend')
			    .addClass('xdsoft_disabled');
			},
			weekends:['01.01.2014','02.01.2014','03.01.2014','04.01.2014','05.01.2014','06.01.2014'],
		});
  	});
</script>
