<?php 
$this->headTitle($this->title); // Titre de la page 
$uneSoutenance = $this->soutenance; // Information du stage
$lesJurys = $this->jurys; // Les demandes de stages des etudiants
?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
			
				<div class="panel-heading">
					<h3 class="panel-title"><?php echo "Soutenance le ".$this->toDmy($uneSoutenance['dateSoutenance'], true)."<br />
														Salle : ".$uneSoutenance['salleSoutenance'];?>
						<br />
					 	<?php if(($this->typeSession == "Enseignant" && $this->isResponsable == true)) { ?>
					 	<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'depot', 'code'=>$uneSoutenance->idSoutenance),"default", true); ?>" class="btn btn-primary">&nbsp; Modifier &raquo; &nbsp;</a>
					 	<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'deletesoutenance', 'code'=>$uneSoutenance->idSoutenance),"default", true); ?>" class="btn btn-danger" id="confirmerDeleteSoutenance">Supprimer &raquo;</a>
					 	<?php } ?>
					 	<span onclick="history.back()" class="navbar-right cursorHand"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour" /></span>
					</h3>
					<br/>
					<h3 class="panel-title"><?php echo $uneSoutenance->libelleStage; ?></h3>
	            </div>
	            
	            <div class="panel-body">
					<?php echo $uneSoutenance->descriptionStage; ?>
					
					<br /><br />
					
				  	<!-- Table -->
					<table class="table text-center">
						<thead>
							<tr>
								<?php if($uneSoutenance->idEtudiant != null) { ?><th class="text-center">Étudiant</th><?php } ?>
								<?php if($uneSoutenance->idEnseignantTuteur != null) { ?><th class="text-center">Tuteur enseignant</th><?php } ?>
								<th class="text-center">Tuteur entreprise</th>
								<th class="text-center">Date début</th>
								<th class="text-center">Date fin</th>
			          		</tr>
		        		</thead>
		        		
		        		<tbody>
							<tr>
								<?php if($uneSoutenance->idEtudiant != null) { ?><td><?php echo $uneSoutenance->nomEtudiant.' '.$uneSoutenance->prenomEtudiant; ?></td><?php } ?>
								<?php if($uneSoutenance->idEnseignantTuteur != null) { ?><td><?php echo $uneSoutenance->nomEnseignant.' '.$uneSoutenance->prenomEnseignant; ?></td><?php } ?>
			            		<td><?php echo $uneSoutenance->nomPersonne.' '.$uneSoutenance->prenomPersonne; ?></td>
					            <td><?php echo $this->toDmy($uneSoutenance->dateDebutStage); ?></td>
					            <td><?php echo $this->toDmy($uneSoutenance->dateFinStage); ?></td>
							</tr>
		        		</tbody>
	      			</table>
	      			
	      			<?php
	      			// ENTREPRISE
	      			if(($this->typeSession == "Entreprise")) { ?>
	      				<?php // LISTE DES JURYS ?>
					  	<!-- Table -->
						<table class="table text-center">
						<caption><h3><span class="label label-primary">&nbsp; Liste des jurys &nbsp;</span></h3></caption>
							<thead>
								<tr>
									<th class="text-center">Jury</th>
									<th class="text-center">Action</th>
				          		</tr>
			        		</thead>
			        		<tbody>
			        		<?php if(count($lesJurys) > 0) { ?>
				        			<?php foreach($lesJurys as $unJury) { ?>
										<?php if ($unJury->idPersonne != null) { ?>
											<tr>
												<td><?php echo $unJury->nomPersonne. ' '.$unJury->prenomPersonne; ?></td>
							            		<td>
							            			<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'deletejury', 'codeSoutenance' =>$uneSoutenance->idSoutenance, 'idPersonne'=>$unJury->idPersonne),"default",true); ?>" class="btn btn-danger stageEtudiantBtnLeft" id="confirmerNePasParticiperSoutenance">&nbsp; Ne pas participer &nbsp;</a>
							            		</td>
											</tr>
										<?php } ?>
									<?php } ?>
							<?php } else { ?>
								<tr><td colspan="2">Aucune composition de jury.</td></tr>
							<?php } ?>
			        		</tbody>
		      			</table>
		      		<?php 
					}	
					?>
					
					<?php
	      			// ENSEIGNANT RESPONSABLE
	      			if(($this->typeSession == "Enseignant" && $this->isResponsable == true)) { ?>
	      				<?php // LISTE DES JURYS ?>
					  	<!-- Table -->
						<table class="table text-center">
						<caption><h3><span class="label label-primary">&nbsp; Liste des jurys &nbsp;</span></h3></caption>
							<thead>
								<tr>
									<th class="text-center">Jury</th>
									<th class="text-center">Action</th>
				          		</tr>
			        		</thead>
			        		<tbody>
			        		<?php if(count($lesJurys) > 0) { ?>
				        			<?php foreach($lesJurys as $unJury) { ?>
										<?php if ($unJury->idPersonne != null) { ?>
											<tr>
												<td><?php echo $unJury->nomPersonne. ' '.$unJury->prenomPersonne; ?></td>
							            		<td><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'deleteJury', 'codeSoutenance'=>$unJury->codeSoutenance, 'idPersonne'=>$unJury->idPersonne)); ?>"><img src="<?php echo $this->baseUrl();?>/images/icone/delete.png" class="btnCrudResponsable" alt="Supprimer" /></a></td>
											</tr>
										<?php } else { ?>
											<tr>
												<td><?php echo $unJury->nomEnseignant. ' '.$unJury->prenomEnseignant; ?></td>
							            		<td><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'deleteJury', 'codeSoutenance'=>$unJury->codeSoutenance, 'idEnseignant'=>$unJury->idEnseignant)); ?>"><img src="<?php echo $this->baseUrl();?>/images/icone/delete.png" class="btnCrudResponsable" alt="Supprimer" /></a></td>
											</tr>
										<?php } ?>
									<?php } ?>
							<?php } else { ?>
								<tr><td colspan="2">Aucune composition de jury.</td></tr>
							<?php } ?>
								<tr><td colspan="2"><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'ajouterjury', 'codeSoutenance'=>$uneSoutenance->idSoutenance), "default", true); ?>" class="btn btn-success stageEtudiantBtnLeft">&nbsp;&nbsp; Ajouter un membre au jury + &nbsp;&nbsp;</a></td></tr>
			        		</tbody>
		      			</table>
		      		<?php 
					}	
					?>
	      		</div>
	      		
			</div>
		</div>
	</div>
</div>


<?php // DIALOG DE CONFIRMATION ?>
<p id="dialog-confirm-delete-soutenance" title="Supprimer soutenance"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment supprimer la soutenance avec sa composition de jurys ?</p>
<p id="dialog-confirm-nepasparticiper-soutenance" title="Ne pas participer à la soutenance"><span class="ui-icon ui-icon-alert" id="dialogConfirm"></span>Voulez-vous vraiment annuler la participation à la soutenance de ce jury ?</p>


<?php // SCRIPT JS UI POUR LE DIALOG ?>
<script>
$(function() {
	var hrefDemande = ''; // Variable qui recupere le chemin url en cas de redirection

	$("#dialog-confirm-delete-soutenance").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 660,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#confirmerDeleteSoutenance").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-delete-soutenance").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});

	$("#dialog-confirm-nepasparticiper-soutenance").dialog({
		autoOpen: false,
      	resizable: false,
      	height:161,
      	width: 620,
      	modal: true,
      	show: { effect: "drop", duration: 400 },
        hide: { effect: "clip", duration: 200 },
      	buttons: { 
       		"Oui": function() { 
           		$(this).dialog("close"); 
           		window.location.href = hrefDemande; // Redirection url
           	}, 
			"Non": function() { 
				$(this).dialog("close");
			} 
		},
    });

	$("#confirmerNePasParticiperSoutenance").click(function(){
		hrefDemande = $(this).attr("href"); // Recupere le lien de la balise <a>
        $("#dialog-confirm-nepasparticiper-soutenance").dialog("open"); // Ouvre la fenetre de dialog
        return false;
	});
});
</script>
 
