<?php 
$this->headTitle($this->title); // Titre de la page 
$uneSoutenance = $this->soutenance; // Information du stage
$lesJurys = $this->jurys; // Les demandes de stages des etudiants
?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="panel panel-default">
			
				<div class="panel-heading">
					<h3 class="panel-title"><?php echo "Soutenance le ".$this->toDmy($uneSoutenance['dateSoutenance'], true)."<br />
														Salle : ".$uneSoutenance['salleSoutenance'];?>
					 	<span onclick="history.back()" class="navbar-right cursorHand"><img src="<?php echo $this->baseUrl();?>/images/glyphicons_free/glyphicons/glyphicons_216_circle_arrow_left.png" alt="Retour" /></span>
					 	<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'depot', 'code'=>$uneSoutenance->idSoutenance),"default", true); ?>" class="btn btn-primary navbar-right" id="btnUpdateSoutenance">Modifier la soutenance &raquo;</a>
					</h3>
					<br/>
					<h3 class="panel-title"><?php echo $uneSoutenance->libelleStage; ?></h3>
	            </div>
	            
	            <div class="panel-body">
					<?php echo $uneSoutenance->descriptionStage; ?>
					
					<br /><br />
					
				  	<!-- Table -->
					<table class="table text-center">
						<thead>
							<tr>
								<?php if($uneSoutenance->idEtudiant != null) { ?><th class="text-center">Étudiant</th><?php } ?>
								<?php if($uneSoutenance->idEnseignantTuteur != null) { ?><th class="text-center">Tuteur enseignant</th><?php } ?>
								<th class="text-center">Tuteur entreprise</th>
								<th class="text-center">Date début</th>
								<th class="text-center">Date fin</th>
			          		</tr>
		        		</thead>
		        		
		        		<tbody>
							<tr>
								<?php if($uneSoutenance->idEtudiant != null) { ?><td><?php echo $uneSoutenance->nomEtudiant.' '.$uneSoutenance->prenomEtudiant; ?></td><?php } ?>
								<?php if($uneSoutenance->idEnseignantTuteur != null) { ?><td><?php echo $uneSoutenance->nomEnseignant.' '.$uneSoutenance->prenomEnseignant; ?></td><?php } ?>
			            		<td><?php echo $uneSoutenance->nomPersonne.' '.$uneSoutenance->prenomPersonne; ?></td>
					            <td><?php echo $this->toDmy($uneSoutenance->dateDebutStage); ?></td>
					            <td><?php echo $this->toDmy($uneSoutenance->dateFinStage); ?></td>
							</tr>
		        		</tbody>
	      			</table>
	      			
	      			<?php 
	      			// ENTREPRISE
	      			if($this->typeSession == "Entreprise") { ?>
		      			<?php // Présent ?>
	      				<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'depot', 'code'=>$uneSoutenance->codeStage),"default", true); ?>" class="btn btn-primary navbar-right stageEtudiantBtnLeft">Participer &raquo;</a>
		      			<?php // Pas présent ?>
		      			<a href="<?php echo $this->url(array('controller'=>'stage', 'action'=>'delete', 'code'=>$uneSoutenance->codeStage),"default", true); ?>" class="btn btn-danger navbar-right stageEtudiantBtnLeft">Ne peux pas participer &raquo;</a>
		      		<?php }
	      			
	      			// ENSEIGNANT RESPONSABLE
	      			if($this->typeSession == "Enseignant" && $this->isResponsable == true) { ?>
	      				<?php // MODIFIER LE STAGE ?>
	      				
	      				
	      				<?php // LISTE DES JURYS ?>
					  	<!-- Table -->
						<table class="table text-center">
						<caption><h3><span class="label label-primary">&nbsp; Liste des jurys &nbsp;</span></h3></caption>
							<thead>
								<tr>
									<th class="text-center">Jury</th>
									<th class="text-center">Action</th>
				          		</tr>
			        		</thead>
			        		<tbody>
			        		<?php if(count($lesJurys) > 0) { ?>
				        			<?php foreach($lesJurys as $unJury) { ?>
										<?php if ($unJury->idPersonne != null) { ?>
											<tr>
												<td><?php echo $unJury->nomPersonne. ' '.$unJury->prenomPersonne; ?></td>
							            		<td><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'delete', 'codeSoutenance'=>$unJury->codeSoutenance, 'idPersonne'=>$unJury->idPersonne)); ?>"><img src="<?php echo $this->baseUrl();?>/images/icone/delete.png" class="btnCrudResponsable" alt="Supprimer" /></a></td>
											</tr>
										<?php } else { ?>
											<tr>
												<td><?php echo $unJury->nomEnseignant. ' '.$unJury->prenomEnseignant; ?></td>
							            		<td><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'delete', 'codeSoutenance'=>$unJury->codeSoutenance, 'idEnseignant'=>$unJury->idEnseignant)); ?>"><img src="<?php echo $this->baseUrl();?>/images/icone/delete.png" class="btnCrudResponsable" alt="Supprimer" /></a></td>
											</tr>
										<?php } ?>
									<?php } ?>
							<?php } else { ?>
								<tr><td colspan="2">Aucune composition de jury.</td></tr>
							<?php } ?>
								<tr><td colspan="2"><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'ajouterjury', 'codeSoutenance'=>$uneSoutenance->idSoutenance)); ?>" class="btn btn-success stageEtudiantBtnLeft">&nbsp;&nbsp; Ajouter un membre au jury + &nbsp;&nbsp;</a></td></tr>
			        		</tbody>
		      			</table>
		      		<?php 
					}	
					?>
	      		</div>
	      		
			</div>
		</div>
	</div>
</div>

