<?php $this->headTitle($this->title); // Titre de la page ?>

<div class="jumbotron">
	<div class="container">
		<div class="row">
		
			<div class="panel panel-default">
				<div class="panel-heading">
	              <h2 class="panel-title">
	              	  Liste des soutenances

					  	<?php // FILTRE ENSEIGNANT RIGHT ?>
						<?php if($this->typeSession == "Enseignant" && $this->isResponsable == 1) { ?>
		  					<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'depot'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Déposer &raquo;</a>
					  		<?php if($this->param == "tuteur"){  ?>
	  							<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'index'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Toutes &raquo;</a> 
		  					<?php } else { ?>
  								<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'index', 'my'=>'tuteur'),"default", true); ?>" class="btn btn-default navbar-right stageEtudiantBtnLeft">Mes soutenances &raquo;</a> 
		  					<?php } 
						} ?>
  					  
  					  <?php // LISTE DEROULANTE DES FORMATIONS ?>
  					  <?php if($this->typeSession != "Etudiant") { ?>
	  					  <li class="dropdown navbar-collapse collapse navbar-right" id="listeFormationStage">
							  <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: black; font-size: 18px;">Formation <b class="caret"></b></a>
		  					  <ul class="dropdown-menu">
		  					  		<li <?php if($this->formation == null) { ?>class="active"<?php } ?>><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'index', 'page'=>null, 'formation'=>null)); ?>">Toutes</a></li>
				                	<li class="divider"></li>
			                	<?php foreach($this->lesFormations as $uneFormation) { ?>
				                	<li <?php if($this->formation == $uneFormation->codeFormation) { ?>class="active"<?php } ?>><a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'index', 'page'=>null, 'formation'=>$uneFormation->codeFormation)); ?>"><?php echo $uneFormation->libelleFormation.' '.$uneFormation->niveauFormation.' '.$uneFormation->specialiteFormation?></a></li>
				                	<li class="divider"></li>
			                	<?php } ?>
			              	  </ul>
			              </li>
			          <?php } ?>
	              </h2>
	            </div>
	            
	            <div class="panel-body">
	            	<?php 
	            	// LISTE DES SOUTENANCES
	            	if(count($this->lesSoutenances) > 0) {
	            		$i = 0;
	            		foreach($this->lesSoutenances as $uneSoutenance) { ?>          
						<div class="list-group">
							<a href="<?php echo $this->url(array('controller'=>'soutenance', 'action'=>'fiche', 'code'=>$uneSoutenance["idSoutenance"])); ?>"class="list-group-item list-group-item-info">
								<h4 class="list-group-item-heading">
									<?php echo "Soutenance le ".$this->toDmy($uneSoutenance['dateSoutenance'], true)."<br />
												Salle : ".$uneSoutenance['salleSoutenance'];?>
								</h4>
								<div class="list-group-item-text">
									<?php echo $uneSoutenance["libelleStage"]; ?>
									<br />
									<?php echo $uneSoutenance["descriptionStage"]; ?>
								</div>
						  	</a>
						</div>
						<?php 
						$i++;
						}
						// Pagination
						echo $this->paginationControl($this->lesSoutenances,'Sliding','common/pagination.phtml'); 
					}
					// Liste de soutenance vide 
					else echo "Aucune soutenance n'a été trouvé."; ?>
	            </div>
			</div>
			
		</div>
	</div>
</div>
